// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCell() {
  return window['go']['main']['App']['ClearCell']();
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetGameState() {
  return window['go']['main']['App']['GetGameState']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function InputNumber(arg1) {
  return window['go']['main']['App']['InputNumber'](arg1);
}

export function LoadGame(arg1) {
  return window['go']['main']['App']['LoadGame'](arg1);
}

export function NewGame(arg1) {
  return window['go']['main']['App']['NewGame'](arg1);
}

export function SaveGame() {
  return window['go']['main']['App']['SaveGame']();
}

export function SelectCell(arg1, arg2) {
  return window['go']['main']['App']['SelectCell'](arg1, arg2);
}

export function TogglePencilMode() {
  return window['go']['main']['App']['TogglePencilMode']();
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}
