// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCell(arg1, arg2) {
  return window['go']['main']['App']['ClearCell'](arg1, arg2);
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetGameState() {
  return window['go']['main']['App']['GetGameState']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function InputNumber(arg1, arg2, arg3) {
  return window['go']['main']['App']['InputNumber'](arg1, arg2, arg3);
}

export function LoadGame(arg1) {
  return window['go']['main']['App']['LoadGame'](arg1);
}

export function NewGame(arg1) {
  return window['go']['main']['App']['NewGame'](arg1);
}

export function RestartGame() {
  return window['go']['main']['App']['RestartGame']();
}

export function SaveGame() {
  return window['go']['main']['App']['SaveGame']();
}

export function ToggleCandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleCandidate'](arg1, arg2, arg3);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}
