// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {game} from '../models';

export function ClearCell():Promise<void>;

export function GetBoard():Promise<engine.SudokuBoard>;

export function GetGameState():Promise<game.GameState>;

export function GetHistory():Promise<Array<game.PuzzleRecord>>;

export function InputNumber(arg1:number):Promise<void>;

export function LoadGame(arg1:string):Promise<void>;

export function NewGame(arg1:string):Promise<void>;

export function SaveGame():Promise<void>;

export function SelectCell(arg1:number,arg2:number):Promise<void>;

export function TogglePencilMode():Promise<boolean>;

export function Undo():Promise<void>;
